experience_conversion:
  - { name: "amethyst_shard", exp: 5, max: 5, min: 0 }
  - { name: "amethyst_block", exp: 20, max: 20, min: 0 }
  - { name: "echo_shard", exp: 200, max: 100, min: 0 }

absorption_apply_mending: true

refine:
  cost_experience: 100
  pickaxes:
    - "stone_pickaxe"
    - "iron_pickaxe"
    - "diamond_pickaxe"
    - "netherite_pickaxe"

  pickaxe_mapping:
    - { from: "iron_ore", to: "iron_ingot" }
    - { from: "deepslate_iron_ore",to: "iron_ingot" }
    - { from: "gold_ore", to: "gold_ingot" }
    - { from: "deepslate_gold_ore",to: "gold_ingot" }
    - { from: "diamond_ore", to: "diamond" }
    - { from: "deepslate_diamond_ore",to: "diamond" }

  axes:
    - "stone_axe"
    - "iron_axe"
    - "diamond_axe"
    - "netherite_axe"

repair:
  cost_level: 100
