experience_conversion:
  - { material: "amethyst_shard", exp: 5, random: 5, mending: true }
  - { material: "amethyst_block", exp: 20, random: 20, mending: true }
  - { material: "echo_shard", exp: 200, random: 100, mending: true }
  - { material: "amethyst_cluster", exp: 15, random: 30, mending: true }

absorb:
  block: "bookshelf"
  item: "book"

refine:
  cost_experience: 100
  pickaxes:
    - "stone_pickaxe"
    - "iron_pickaxe"
    - "diamond_pickaxe"
    - "netherite_pickaxe"

  pickaxe_mapping:
    - { from: "iron_ore", to: "iron_ingot" }
    - { from: "deepslate_iron_ore", to: "iron_ingot" }
    - { from: "gold_ore", to: "gold_ingot" }
    - { from: "deepslate_gold_ore", to: "gold_ingot" }
    - { from: "diamond_ore", to: "diamond" }
    - { from: "deepslate_diamond_ore", to: "diamond" }

  axes:
    - "stone_axe"
    - "iron_axe"
    - "diamond_axe"
    - "netherite_axe"

repair:
  cost_level: 2
